<div id='main-header'><h1></h1></div>
<div class="section">
  <p>MathSoc has many different volunteer opportunities available depending on what you're interested in doing and how much time you have to contribute.  Some of these are included below, ordered by time commitment.  Note that this is not a complete list, so if you don't see something that perks your interest, try emailing {mailto address="VPAS@mathsoc.uwaterloo.ca" encode="javascript_charcode"} or just drop by MC3039 and talk to one of the executive to learn about other positions.</p>

  <p>Many people start by <a href="{$baseUrl/office/signup}">signing up to hold an office hour</a> in the society office (MC 3038).  This involves a commitment of one hour each week to keep the office open for business.  You'll provide other students with access to our textbook library, novelties, games, school supplies, printing, photocopying and binding facilities as well as providing information about the society.  Our office is entirely volunteer run and we wouldn't be able to provide many of our services without our wonderful office volunteers.  If you have questions, you can email {mailto address="office@mathsoc.uwaterloo.ca" encode="javascript_charcode"} for more information.</p>

  <p>MathSoc Council is the main decision making body of the society.  They decide how the student fees are allocated and make structual changes to the society.  This council is made up of the executive of the society, and plan and class representatives.  If you want to learn more about the student societies, services, administration or faculties on campus, and make decisions that matter, then this is a good place to be.  If you're in first year, a society representative will be around to your class in the first few weeks to elect a class rep.  If you missed it or are an upper year student, you can <a href="{$baseUrl}/positions/councillors">nominate yourself for a plan rep position</a>.</p>

  <p>There are also many directorships to choose from with a wide range of time commitments.  As a director you run a service of the society.  You will create a budget with the help of the executive and make decisions about the administration of the service.  Depending on the position, you may also have to manage other volunteers.  This is a great opportunity to get some leadership or management experience or help to improve the services we provide to students.  If you think you would be interested in a directorship, see <a href="{$baseUrl}/positions/directorships">a full listing of available directorships</a>.</p>

  <p>The executives of the society have the largest time commitment and responsibility.  They manage all the other volunteers to ensure the society continues to provide services and events smoothly.  They also provide a voice and representation for council to the faculty and other university bodies.  If you think your up to the challenge, email the president ({mailto address="prez@mathsoc.uwaterloo.ca" encode="javascript_charcode"}) for more information</p>

  <p>Note that this is not a complete list, so if you don't see something that perks your interest, try emailing {mailto address="VPAS@mathsoc.uwaterloo.ca" encode="javascript_charcode"} or just drop by MC3039 and talk to one of the executive.</p>

  <p>Whether you're looking for a great experience, or to make a difference in your school, MathSoc has a way for you to get involved.</p>
</div>
