<?php

$menu = array(
	array(
		"title"	=> "Announcements",
		"link"	=> "",
		"sub"	=> array(
		array(
			"title" => "Events Calendar",
			"link" => ""))),
	array(
		"title"	=> "Services",
		"link"	=> "/Services",
		"sub"	=> array(
		array(
			"title"	=> "Exambank",
			"link"	=> "/Exambank",
			"sub"	=> array()),
		array(
			"title"	=> "Lockers",
			"link"	=> "/Lockers",
			"sub"	=> array()),
		array(
			"title"	=> "Office",
			"link"	=> "/Office",
			"sub"	=> array()),
		array(
			"title"	=> "Novelties",
			"link"	=> "/Novelties",
			"sub"	=> array()),
		array(
			"title"	=> "C&D",
			"link"	=> "/CandD",
			"sub"	=> array()),
		array(
			"title"	=> "C.I.F.",
			"link"	=> "/CIF",
			"sub"	=> array()),
		array(
			"title"	=> "Mathletics",
			"link"	=> "/Mathletics",
			"sub"	=> array()),
		array(
			"title"	=> "Student Space",
			"link"	=> "/Space",
			"sub"	=> array()))),
	array(
		"title"	=> "Academics",
		"link"	=> "/Academics",
		"sub"	=> array(
		array(
			"title" => "Events Calendar",
			"link" => ""))),
	array(),
	array());

/*
    <li><a href='/academics/' accesskey='2'>Academics</a>
      <ul>
        <li><a href='/academic/committees.php'>School Committees</a></li>
        <li><a href='/academic/reps.php'>Academic Reps</a></li>
        <li><a href='/academic/lists.php'>Mailing Lists</a></li>
      </ul>
    </li>
    <li><a href='/council/' accesskey='3'>Council</a>
      <ul>

        <li><a href='/council/members.php'>Composition</a></li>
        <li><a href='/council/minutes/'>Meeting Minutes</a></li>
        <li><a href='/Pinkbook/'>Bylaws &amp; Policies</a></li>
        <li><a href='/council/vacancies.php'>Available Positions</a></li>
        <li><a href='http://www.mathsoc.uwaterloo.ca/cgi-bin/mailman/listinfo/council'>Join the Mailing List</a></li>

      </ul>
    </li>
    <li><a href='/volunteers.php' accesskey='4'>Volunteers</a>
      <ul>
        <li><a href='/getinvolved.php'>How to Get Involved</a></li>
        <li><a href='http://wiki.mathsoc.uwaterloo.ca'>Wiki</a></li>
        <li><a href='/secure/'>Secure Access</a></li>

      </ul>
    </li>
    <li><a href='/clubs/' accesskey='5'>Clubs</a>
      <ul>
        <li><a href=''>Join a Club</a></li>
      </ul>
    </li>
    <li><a href='/committees.php' accesskey='6'>Committees</a>

      <ul>
        <li><a href='http://orientation.math.uwaterloo.ca/'>Math Orientation</a></li>
    <li><a href='http://mathnews.uwaterloo.ca'><i>math</i><b>NEWS</b></a></li>
    <li><a href='http://www.student.math.uwaterloo.ca/~mgc'>Math Grad Committee</a></li>
      </ul>
    </li>
    <li><a href='/contact.php' accesskey='7'>Contact Info</a></li>
  </ul>
*/
